spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineStoreDB
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations: file:///C:/Users/Tartog/OnlineStore/Images/